# database相关配置
mysql:
  host: 10.10.6.28
  port: 3306
  db: tcc_drm
  username: root
  password: Tcinterlib@123...
# redis缓存相关配置
redis:
  host: 10.10.6.24
  port: 31379

forest:
  base-address-scheme: https
  base-address-host: tcc-test.interlib.com.cn
  base-address-port: 443
  log-enabled: false

prop:
  upload-folder: /home/miniodata/video
  hls-folder: /usr/local/src/nginx/hls

#加密key文件地址
media-stream:
  decrypt-path: /usr/local/src/nginx/hls/
  key-name: enc
  file-extension: .key
  info-file-extension: .keyinfo
  uri: http://j.tcsoft.info:38082/prod-api/client-api/mediaStream/decrypt?streamToken=%s&identifier=%s


doc:
  enable: false
  production: true

es:
  host: 10.10.6.24
  port: 30200
  scheme: http
  enable-auth: true
  username: elastic
  password: fY9FKYGNCZwIuAm=f784
  connect-timeout: 5000
  socket-timeout: 5000
  connection-request-timeout: 5000
  max-connect-num: 100
  max-connect-per-route: 100

google:
  cloud:
    proxy-enable: true
    proxy-host: 127.0.0.1
    proxy-port: 19180
    key-path: /key/googleKey.json
    bucket-name: tc_test_20220209
    bucket-path: audio/audio-files/
    transcript: audio/transcripts/


orc:
  xunfei:
    api-secret: MDdiYjFjZjcyNzQ4YjUyZTAxNmJkMzI0
    api-key: 1999e1860880accacccc6d66ea8e67cc
    app-id: fdcc912c
    request-url: https://api.xf-yun.com/v1/private/sf8e6aca1